# Default values for api-finder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: jwproencio/iti-challenge
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  averageUtilization: 70

updateStrategy: {}
#   type: RollingUpdate
#   rollingUpdate:
#     maxSurge: 20%
#     maxUnavailable: 0

## Annotations to be added to application pods
podAnnotations: {}

# labels to add to the pod container metadata
podLabels: {}
#   key: value

containerPort: 8080
healthCheckPath: "/"

livenessProbe:
  initialDelaySeconds: 
  periodSeconds: 60
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 5
  failureThreshold: 10

resources:
  limits:
    cpu: 200m
    memory: 512Gi
  requests:
    cpu: 100m
    memory: 256Mi 

service:
  type: ClusterIP
  loadBalancerIP: ""
  port: 8080
  annotations: {}

nodeSelector: {}
affinity: {}
tolerations: []
